/* 
	PostgreSQL/pgbench version of AdventureWorks Execution Plan Demonstration
	
	This script demonstrates various execution plan operators for educational purposes.
	
	Note: This script uses temporary tables and index operations which should be run
	separately as a setup script, not with pgbench. The queries below are the 
	demonstration queries without the temp table setup.
	
	For actual execution plan analysis in PostgreSQL:
	- Use EXPLAIN (ANALYZE, BUFFERS) instead of SET STATISTICS XML
	- PostgreSQL does not use RID/KEY lookups, uses Heap Fetch/Index Scan
	- Create indexes with similar patterns on permanent tables
	
	Usage:
	  pgbench -c <num_clients> -j <num_threads> -T <duration_seconds> -f AdventureWorks_ExecutionPlan_pgbench.sql -r adventureworks
	
	This Sample Code is provided for the purpose of illustration only and is not intended
	to be used in a production environment. THIS SAMPLE CODE AND ANY RELATED INFORMATION ARE
	PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT
	NOT LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR
	PURPOSE.
*/

-- Regenerated by pgbench for each transaction.
\set personid random(1, 20777)
\set birthyear random(1951, 1991)
\set customerid random(11000, 30118)
\set productid random(316, 999)

-- Query 1: Simple join demonstrating execution plan operators
SELECT p.title || ' ' || p.firstname || ' ' || p.lastname AS fullname,
       c.accountnumber,
       s.name
FROM   person.person AS p
       INNER JOIN sales.customer AS c
       ON c.personid = p.businessentityid
       INNER JOIN sales.store AS s
       ON s.businessentityid = c.storeid
WHERE  p.businessentityid = :personid;

-- Query 2: Loop joins example
SELECT firstname,
       lastname,
       a.modifieddate
FROM   person.person AS p
       INNER JOIN humanresources.employee AS e
       ON p.businessentityid = e.businessentityid
       INNER JOIN person.businessentityaddress AS a
       ON e.businessentityid = a.businessentityid
WHERE  EXTRACT(YEAR FROM e.birthdate) = :birthyear;

-- Query 3: Hash match example
SELECT soh.billtoaddressid
FROM   sales.customer AS c
       LEFT OUTER JOIN sales.salesorderheader AS soh
       ON c.customerid = soh.customerid
WHERE  c.customerid = :customerid;

-- Query 4: Merge join example
SELECT poh.purchaseorderid,
       poh.orderdate,
       pod.productid,
       pod.duedate,
       poh.vendorid
FROM   purchasing.purchaseorderheader AS poh
       INNER JOIN purchasing.purchaseorderdetail AS pod
       ON poh.purchaseorderid = pod.purchaseorderid
WHERE  pod.productid = :productid;

-- Query 5: Hash match with credit card join
SELECT soh.purchaseordernumber,
       soh.accountnumber,
       sod.orderqty,
       sod.linetotal,
       c.cardnumber
FROM   sales.salesorderheader AS soh
       INNER JOIN sales.salesorderdetail AS sod
       ON soh.salesorderid = sod.salesorderid
       INNER JOIN sales.creditcard AS c
       ON soh.creditcardid = c.creditcardid
WHERE  soh.customerid = :customerid;

-- Query 6: Hash + parallelism with ORDER BY
SELECT p.name,
       sod.orderqty,
       sod.unitprice
FROM   production.product AS p
       INNER JOIN sales.salesorderdetail AS sod
       ON p.productid = sod.productid
WHERE  sod.productid = :productid
ORDER BY p.name DESC;

-- Query 7: Hash + parallelism without ORDER BY
SELECT p.name,
       sod.orderqty,
       sod.unitprice
FROM   production.product AS p
       INNER JOIN sales.salesorderdetail AS sod
       ON p.productid = sod.productid
WHERE  sod.productid = :productid;
